name: APK Uretici

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Java (JDK 17) Kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Paketleri Yukle
        run: npm install

      - name: Android Klasorunu Oluştur (Prebuild)
        run: npx expo prebuild --platform android

      - name: Android APK Build Al
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: APK Dosyasini Indirilebilir Yap
        uses: actions/upload-artifact@v4
        with:
          name: HuzurVakti-App
          path: android/app/build/outputs/apk/release/app-release.apk
